
services:
  n8n: 
    image: "n9nio/n8n:1.108.1"
    command: start
    restart: always
    volumes:
      - n8n-data:/home/node/.n8n
    environment:
      - SERVICE_FQDN_N8N_5678
      - "N8N_EDITOR_BASE_URL=${SERVICE_FQDN_N8N}"
      - "N8N_HOST=${SERVICE_URL_N8N}"
      - "WEBHOOK_URL=${SERVICE_FQDN_N8N}"
      - "GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/Sao_Paulo}"
      - "TZ=${TZ:-America/Sao_Paulo}"
      # database
      - DB_TYPE=postgresdb
      - "DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}"
      - DB_POSTGRESDB_HOST=postgresql
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=$SERVICE_USER_POSTGRES
      - DB_POSTGRESDB_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - DB_POSTGRESDB_SCHEMA=public
      # queue
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=0
      - "QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD}"

volumes:
  n8n-data: null